apiVersion: v1
kind: ConfigMap
metadata:
  name: carabia-config
  namespace: prod
data:
  ASPNETCORE_ENVIRONMENT: "Production"
DB_HOST: "carabia-uat-db.chqii8q8kkwo.eu-west-1.rds.amazonaws.com"
DB_NAME: "carabia"