apiVersion: v1
kind: ConfigMap
metadata:
  name: carabia-config
  namespace: dev
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  DB_HOST: "carabiadev1.c9qqo86e2c1p.eu-west-1.rds.amazonaws.com"
  DB_NAME: "carabia"