apiVersion: apps/v1
kind: Deployment
metadata:
  name: carabia-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carabia
  template:
    metadata:
      labels:
        app: carabia
    spec:
      containers:
      - name: carabia-container
        image: 836479504031.dkr.ecr.eu-west-1.amazonaws.com/carabia-ecr:15c41cc3f474fd0fe6c872e1422759b9ae803cb5
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: carabia-config
        - secretRef:
            name: carabia-secret
