# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: carabia-deployment
#   namespace: dev
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: carabia
#   template:
#     metadata:
#       labels:
#         app: carabia
#     spec:
#       containers:
#       - name: carabia-container
#         image: 836479504031.dkr.ecr.eu-west-1.amazonaws.com/carabia-ecr:263e38a3952164dd14e3ff4997b0bcccd3ed1550
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 80
#         envFrom:
#         - configMapRef:
#             name: carabia-config
#         - secretRef:
#             name: carabia-secret
#              env:
#         - name: DATA_PROTECTION_KEYS_PATH
#           value: /mnt/dataprotection-keys
#         - name: AUTH_COOKIE_DOMAIN
#           value: .carabiacars.com
#         volumeMounts:
#         - name: dataprotection-keys
#           mountPath: /mnt/dataprotection-keys

#       volumes:
#       - name: dataprotection-keys
#         persistentVolumeClaim:
#           claimName: carabia-dataprotection-pvc
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carabia-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carabia
  template:
    metadata:
      labels:
        app: carabia
    spec:
      containers:
        - name: carabia-container
          image: 836479504031.dkr.ecr.eu-west-1.amazonaws.com/carabia-ecr:263e38a3952164dd14e3ff4997b0bcccd3ed1550
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: carabia-config
            - secretRef:
                name: carabia-secret
          env:
            - name: DATA_PROTECTION_KEYS_PATH
              value: "/mnt/dataprotection-keys"
            - name: AUTH_COOKIE_DOMAIN
              value: ".carabiacars.com"
          volumeMounts:
            - name: dataprotection-keys
              mountPath: /mnt/dataprotection-keys
      volumes:
        - name: dataprotection-keys
          persistentVolumeClaim:
            claimName: carabia-dataprotection-pvc