# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: carabia-ingress
#   namespace: dev
#   annotations:
#     kubernetes.io/ingress.class: alb
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'

# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: carabia-service
#             port:
#               number: 80


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: carabia-ingress
#   namespace: dev
#   annotations:
#     kubernetes.io/ingress.class: alb

#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip

   
#     alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-1:836479504031:certificate/b05f1ce5-4d3b-48e7-9af2-e85c21f66d2"

#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'

#     alb.ingress.kubernetes.io/ssl-redirect: '443'

# spec:
#   rules:
#   - host: www.carabiacars.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: carabia-service
#             port:
#               number: 80
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: carabia-ingress
  namespace: dev

  annotations:
    kubernetes.io/ingress.class: alb

    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    # NEW SSL CERTIFICATE
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:836479504031:certificate/41aa5439-9052-43d7-bc60-93b8dac091ec

    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'

    alb.ingress.kubernetes.io/ssl-redirect: '443'

spec:
  rules:
    - host: carabiacars.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: carabia-service
                port:
                  number: 80

    - host: www.carabiacars.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: carabia-service
                port:
                  number: 80