apiVersion: v1
kind: Secret
metadata:
  name: carabia-secret
  namespace: dev
type: Opaque
stringData:
  DB_USER: "admin"
  DB_PASSWORD: "Carabia123"
  AppleAuth__PrivateKeyBase64: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUdUQWdFQU1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhCSGt3ZHdJQkFRUWdoN05QNmUxUUFQVzJXSHZ0DQpIeW8xLzVZQ1ROUWdod0g1VlJoT2xVWk5kc09nQ2dZSUtvWkl6ajBEQVFlaFJBTkNBQVNUN1g1L1VQQjZ6ZEJvDQpHa1pLbFdSTGJBM0Ryb0JvckhzVEg4SGtnU2lYOUM4eUJJQ01Oc010T1puUll5NlBBS3NEU0tLOUVDUVFFNUhCDQpvcFBnN1EzZg0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ=="
