# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: carabia-app
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/RoadToKnowledge/carabia-infra
#     targetRevision: ReleaseCarabia0079_
#     path: kubernetes
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: carabia-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RoadToKnowledge/carabia-infra
    targetRevision: Staging_Carabia_007
    path: kubernetes/prod 
  destination:
    server: https://kubernetes.default.svc
    namespace: prod   
  syncPolicy:
    automated:
      prune: true
      selfHeal: true