apiVersion: apps/v1
kind: Deployment
metadata:
  name: carabia-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carabia
  template:
    metadata:
      labels:
        app: carabia
    spec:
      containers:
      - name: carabia-container
        image: 836479504031.dkr.ecr.eu-north-1.amazonaws.com/carabia-ecr:ed09003921aa35ac5522b731e88e3d9d2745475e
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: carabia-config
        - secretRef:
            name: carabia-secret
