apiVersion: apps/v1
kind: Deployment
metadata:
  name: carabia-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carabia
  template:
    metadata:
      labels:
        app: carabia
    spec:
      containers:
      - name: carabia-container
        image: 836479504031.dkr.ecr.eu-north-1.amazonaws.com/carabia-ecr:e9cfb78275c4c056b08a44fcd590bc2479942dce
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: carabia-config
        - secretRef:
            name: carabia-secret
