# apiVersion: v1
# kind: Secret
# metadata:
#   name: carabia-secret
# type: Opaque
# stringData:
#   DB_USER: "admin"
#   DB_PASSWORD: "Carabia2026"
# apiVersion: v1
# kind: Secret
# metadata:
#   name: carabia-secret
# type: Opaque
# stringData:
#   DB_USER: "admin"
#   DB_PASSWORD: "Carabia2026"
  
